name: auth_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  localization: ^2.1.0
  intl: any

  # state management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc: ^8.0.1

  # svg
  flutter_svg: ^2.0.7

  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mockito: ^5.4.2

  common:
    git:
      url: https://github.com/cincinnatiai/flutter_common_library.git
      ref: main

  auth_common:
    git:
      url: https://github.com/cincinnatiai/flutter_auth_common.git
      ref: main
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  injectable_generator:
  # Run this command to rebuild dependencies flutter pub run build_runner build --delete-conflicting-outputs
  build_runner:

  retrofit_generator: ">=4.0.0 <5.0.0"

  json_serializable: ">4.8.0"

flutter:
